# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wEJb0ntrRTlYnjxIqsvXBYUy4yAAhWVb

#Ejercicio 2 elaborado por James Jerry Linares Jimenez

#Importar DataFrame de CIA
"""

from IPython.display import IFrame
ciaLink2="https://www.cia.gov/the-world-factbook/field/revenue-from-forest-resources/country-comparison"
IFrame(ciaLink2, width=900, height=900)

import pandas as pd

forestDFs=pd.read_html(ciaLink2, # link
                        header=0, # where is the header?
                        flavor='bs4')

forest=forestDFs[0].copy()

forest

df = pd.DataFrame(forest)

"""#Remplazar '%' por 'pct' en los nombres de las columnas que terminan en '%'"""

df.columns = df.columns.str.replace('%', 'pct')

"""#Mantener solo las columnas requeridas: Country, pct of GDP y Date of Information"""

df = df.drop(columns=[col for col in df.columns if col not in ['Country', 'pct of GDP', 'Date of Information']])

"""#Cambiar el nombre de la columna Date of Information a forest_date"""

df = df.rename(columns={'Date of Information': 'forest_date'})

"""#Eliminar espacios en los nombres de las columnas"""

df.columns = df.columns.str.replace(' ', '')

"""#Eliminar espacios al principio y al final de los valores de las celdas de texto"""

df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

"""#Mantener solo el año en la columna forest_date"""

df['forest_date'] = df['forest_date'].str.extract(r'(\d{4})')

"""#Mostra el df depurado"""

print(df)